{
 "title": "HPC 集群监控",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "任务",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(node_uname_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "cpu_model",
    "label": "CPU 型号",
    "query": "label_values(node_cpu_info{job=~\"$job\", instance=~\"$instance\"}, model_name)"
   },
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(node_uname_info{job=~\"$job\", instance=~\"$instance\"}, nodename)"
   }
  ]
 },
 "panels": [
  { "title": "节点数量和资源统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "节点数"
    }
   ]
  },
  {
   "title": "节点状态",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (state) (node_systemd_unit_state{job=~\"$job\", instance=~\"$instance\", name=\"node_exporter.service\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "最新 CPU 核调度率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg by(instance)(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "核调度率"
    }
   ]
  },
  {
   "title": "最新 CPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - avg by(instance)(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU 使用率"
    }
   ]
  },
  {
   "title": "最新内存使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"} / node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}) * 100)",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "title": "CPU 总核数（核）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count without(cpu,mode)(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}))",
     "legendFormat": "总核数"
    }
   ]
  },
  {
   "title": "CPU 空闲核数（核）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count without(cpu,mode)(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"})) - sum(ceil(avg by(instance)(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode!=\"idle\"}[$__rate_interval])) * count without(cpu,mode)(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"})))",
     "legendFormat": "空闲核数"
    }
   ]
  },
  {
   "title": "内存总量（GB）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}) / 1e9",
     "legendFormat": "内存总量"
    }
   ]
  },
  {
   "title": "内存空闲量（GB）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"}) / 1e9",
     "legendFormat": "空闲内存"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance)(100 - rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[$__rate_interval]) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU 核调度率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance)(1 - rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[$__rate_interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU 一分钟负载",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} load1"
    }
   ]
  },
  {
   "title": "已使用 CPU 核数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count without(cpu,mode)(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}))",
     "legendFormat": "CPU 总核数"
    },
    {
     "expr": "sum(ceil(avg by(instance)(rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode!=\"idle\"}[$__rate_interval])) * count without(cpu,mode)(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"})))",
     "legendFormat": "已用 CPU 核数"
    }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"} / node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "已使用内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}) / 1e9",
     "legendFormat": "内存总量"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"} - node_memory_MemAvailable_bytes{job=~\"$job\",instance=~\"$instance\"}) / 1e9",
     "legendFormat": "已使用内存"
    }
   ]
  },
  {
   "title": "已使用交换分区",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{job=~\"$job\",instance=~\"$instance\"}) / 1e9",
     "legendFormat": "交换分区总量"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes{job=~\"$job\",instance=~\"$instance\"} - node_memory_SwapFree_bytes{job=~\"$job\",instance=~\"$instance\"}) / 1e9",
     "legendFormat": "已使用交换分区"
    }
   ]
  },
  {
   "title": "交换分区使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_memory_SwapFree_bytes{job=~\"$job\",instance=~\"$instance\"} / node_memory_SwapTotal_bytes{job=~\"$job\",instance=~\"$instance\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "已使用临时分区",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",mountpoint=\"/tmp\"}) / 1e9",
     "legendFormat": "临时分区总量"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",mountpoint=\"/tmp\"} - node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",mountpoint=\"/tmp\"}) / 1e9",
     "legendFormat": "已使用临时分区"
    }
   ]
  },
  {
   "title": "临时分区使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_free_bytes{job=~\"$job\",instance=~\"$instance\",mountpoint=\"/tmp\"} / node_filesystem_size_bytes{job=~\"$job\",instance=~\"$instance\",mountpoint=\"/tmp\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}